main:
  entity: "yannicknkongolo7-wgu"
  project_name: nyc_airbnb
  experiment_name: development
  steps: all
  components_repository: "https://github.com/udacity/Project-Build-an-ML-Pipeline-Starter.git#components"


etl:
  sample: "sample1.csv"
  min_price: 10    # dollars
  max_price: 350   # dollars

data_check:
  kl_threshold: 0.2
  # Added for the pytest-based checks
  min_rows: 10
  max_rows: 500000

modeling:
  # Fraction of data to use for test (the remaining will be used for train+val)
  test_size: 0.2
  # Fraction of remaining data to use for validation
  val_size: 0.2
  # Fix this for reproducibility
  random_seed: 42
  # Column for stratification (use "none" for no stratification)
  stratify_by: "neighbourhood_group"
  # Keep this aligned with your training runs
  max_tfidf_features: 500

  # RandomForest hyperparameters (extend as needed)
  random_forest:
    n_estimators: 100
    max_depth: 15
    min_samples_split: 4
    min_samples_leaf: 3
    n_jobs: -1             # -1 means all cores
    criterion: squared_error
    max_features: 0.5
    oob_score: true
